elasticsearch:
  restart: always
  image: elasticsearch:latest
  volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 65536
  log_opt:
    max-size: 50m
    max-file: "1"

logstash:
  restart: always
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "12201:12201/udp"
  links:
    - elasticsearch
  log_opt:
    max-size: 50m
    max-file: "1"

kibana:
  restart: always
  image: kibana
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    NODE_OPTIONS: "--max-old-space-size=200"
  log_opt:
    max-size: 50m
    max-file: "1"
